kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: quay
  labels:
    quay-component: quay-app-route
  annotations:
    quay-component: route
    haproxy.router.openshift.io/timeout: 1h
spec:
  host: $(SERVER_HOSTNAME)
  to:
    kind: Service
    name: quay-app
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
