# Overlay variant for upgrading to current Project Quay release.
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./quay-pg-upgrade.job.yaml
  - ./quay-pg-old.persistentvolumeclaim.yaml
  - ./quay-pg-old.deployment.yaml
patches:
  - path: ./quay.deployment.patch.yaml
  - path: ./quay-pg.deployment.patch.yaml
