apiVersion: batch/v1
kind: Job
metadata:
  name: quay-postgres-upgrade
  labels:
    quay-component: quay-postgres-upgrade
  annotations:
    quay-component: quay-postgres-upgrade
spec:
  template:
    spec:
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 180
      serviceAccountName: quay-database
      volumes:
        - name: postgres-conf-sample
          configMap:
            name: postgres-conf-sample
        - name: postgres-bootstrap
          secret:
            secretName: postgres-bootstrap
        - name: postgres-data
          persistentVolumeClaim:
            claimName: quay-database-13
      containers:
        - name: postgres-new
          image: centos/postgresql-13-centos7@sha256:71b24684d64da46f960682cc4216222a7e4ed8b1a31dd5a865b3e71afdea20d2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_MIGRATION_REMOTE_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-config-secret
                  key: database-name
            - name: POSTGRESQL_MIGRATION_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-config-secret
                  key: database-root-password
            - name: POSTGRESQL_SHARED_BUFFERS
              value: 256MB
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: "2000"
          volumeMounts:
            - name: postgres-conf-sample
              mountPath: /usr/share/pgsql/postgresql.conf.sample
              subPath: postgresql.conf.sample
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
            - name: postgres-bootstrap
              mountPath: /usr/share/container-scripts/postgresql/start/create-extensions.sh
              subPath: create-extensions.sh
              readOnly: true
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
          command:
            - "run-postgresql"
          args:
            - "--version"
  backoffLimit: 20
