apiVersion: batch/v1
kind: Job
metadata:
  name: quay-postgres-upgrade
  labels:
    quay-component: quay-postgres-upgrade
  annotations:
    quay-component: quay-postgres-upgrade
spec:
  template:
    spec:
      restartPolicy: OnFailure
      terminationGraceperiodSeconds: 600
      serviceAccountName: quay-database
      volumes:
        - name: postgres-conf-sample
          configMap:
            name: postgres-conf-sample
        - name: postgres-bootstrap
          secret:
            secretName: postgres-bootstrap
        - name: postgres-data
          persistentVolumeClaim:
            claimName: quay-postgres-13
      containers:
        - name: postgres-upgrade
          image: quay.io/sclorg/postgresql-13-c9s:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_MIGRATION_REMOTE_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-config-secret
                  key: database-name
            - name: POSTGRESQL_MIGRATION_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-config-secret
                  key: database-root-password
            - name: POSTGRESQL_SHARED_BUFFERS
              value: 256MB
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: "2000"
          volumeMounts:
            - name: postgres-conf-sample
              mountPath: /usr/share/pgsql/postgresql.conf.sample
              subPath: postgresql.conf.sample
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
          command:
            - "/bin/sh"
            - "-c"
          args:
            - >
              run-postgresql --version || (echo "postgres migration command failed, cleaning up..." && rm -rf /var/lib/pgsql/data/* && exit 1)
  backoffLimit: 50
