apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clair-postgres-13
  labels:
    quay-component: clair-postgres
  annotations:
    quay-component: clair-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
