FROM registry.redhat.io/ubi9/go-toolset:1.25 AS builder

WORKDIR /workspace

COPY go.mod go.mod
COPY go.sum go.sum
COPY vendor vendor

COPY main.go main.go
COPY apis/ apis/
COPY controllers/ controllers/
COPY pkg/ pkg/

RUN GOEXPERIMENT=strictfipsruntime CGO_ENABLED=1 go build -tags strictfipsruntime -mod vendor -o manager main.go

FROM registry.redhat.io/ubi9/ubi-minimal:latest

LABEL com.redhat.component="quay-operator-container"
LABEL name="quay/quay-rhel9-operator"
LABEL io.k8s.display-name="Red Hat Quay Operator"
LABEL io.k8s.description="Red Hat Quay Operator image"
LABEL io.openshift.tags="quay"
LABEL summary="Red Hat Quay Operator"
LABEL description="Red Hat Quay Operator"
LABEL vendor="Red Hat, Inc."
LABEL maintainer="quay-devel@redhat.com"

ENV QUAY_DEFAULT_BRANDING="redhat"

WORKDIR /workspace
COPY --from=builder /workspace/manager manager
COPY kustomize/ kustomize/

ENTRYPOINT ["/workspace/manager"]
