apiVersion: v1
kind: ConfigMap
metadata:
  name: clair-postgres-conf-sample
data:
  postgresql.conf.sample: |
    huge_pages = off
    logging_collector = on
    log_filename = 'postgresql-%a.log'
    log_truncate_on_rotation = on
    log_rotation_age = 1d
    log_rotation_size = 0
