apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-app-upgrade
spec:
  template:
    metadata:
      labels:
        quay-component: quay-app-upgrade
    spec:
      # Init conatainer needed to wait for Clair to initialize (can take minutes) before attempting to validate config.
      initContainers:
        - name: quay-app-upgrade-init
          image: quay.io/alecmerdler/quay@sha256:2dd5687703c5e92325b4870d516bc595d12b70fb0762a9de2116302e34daf033
          command:
            - /bin/sh
            - -c
            - curl $CLAIR_SERVICE_HOST
          env:
            - name: CLAIR_SERVICE_HOST
              value: $(CLAIR_SERVICE_HOST)
