---
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: testreg
spec:
  components:
  - kind: clairpostgres
    managed: false
  - kind: quay
    managed: true
  - kind: postgres
    managed: true
  - kind: clair
    managed: true
  - kind: redis
    managed: true
  - kind: horizontalpodautoscaler
    managed: true
  - kind: objectstorage
    managed: true
  - kind: route
    managed: true
  - kind: mirror
    managed: true
  - kind: monitoring
    managed: true
  - kind: tls
    managed: true
status:
  conditions:
  - type: ComponentHPAReady
  - type: ComponentRouteReady
  - type: ComponentMonitoringReady
  - type: ComponentPostgresReady
  - type: ComponentObjectStorageReady
  - type: ComponentClairReady
  - message: ClairPostgres not managed by the operator
    reason: ComponentNotManaged
    status: "True"
    type: ComponentClairPostgresReady
  - type: ComponentTLSReady
  - type: ComponentRedisReady
  - type: ComponentQuayReady
  - type: ComponentMirrorReady
  - type: Available
  - type: RolloutBlocked
    message: clairpostgres component unmanaged but no clair postgres config provided
    reason: ConfigInvalid
    status: "True"
