apiVersion: apps/v1
kind: Deployment
metadata:
  name: skynet-quay-app
spec:
  template:
    spec:
      containers:
        - name: quay-app
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skynet-quay-database
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skynet-clair-app
spec:
  template:
    spec:
      containers:
        - name: clair-app
          resources:
            limits:
              cpu: 300m
              memory: 300Mi
            requests:
              cpu: 300m
              memory: 300Mi
