apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: skynet
spec:
  components:
    - kind: quay
      managed: true
      overrides:
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
    - kind: postgres
      managed: true
      overrides:
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
    - kind: clair
      managed: true
      overrides:
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 300m
            memory: 300Mi
