---
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: hpa
spec:
  components:
  - kind: clair
    managed: true
  - kind: clairpostgres
    managed: true
  - kind: quay
    managed: true
  - kind: postgres
    managed: true
  - kind: redis
    managed: true
  - kind: horizontalpodautoscaler
    managed: false
  - kind: objectstorage
    managed: true
  - kind: route
    managed: true
  - kind: mirror
    managed: true
  - kind: monitoring
    managed: true
  - kind: tls
    managed: true
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-clair-app
spec:
  minReplicas: 3
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-quay-app
spec:
  minReplicas: 3
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-quay-mirror
spec:
  minReplicas: 3