apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-quay-app
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: quay-component
                  operator: In
                  values:
                  - quay-app
              topologyKey: kubernetes.io/hostname
            weight: 100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-clair-app
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: quay-component
                  operator: In
                  values:
                  - clair-app
              topologyKey: kubernetes.io/hostname
            weight: 100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-quay-mirror
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: quay-component
                  operator: In
                  values:
                  - quay-mirror
              topologyKey: kubernetes.io/hostname
            weight: 100            
