apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-quay-app
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: quay-component
                operator: In
                values:
                - quay-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-clair-app
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: quay-component
                operator: In
                values:
                - clair-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-quay-mirror
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: quay-component
                operator: In
                values:
                - quay-mirror
