apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: affinity
spec:
  components:
  - kind: quay
    managed: true
    overrides:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: quay-component
                operator: In
                values:
                - quay-app
            topologyKey: kubernetes.io/hostname
  - kind: postgres
    managed: true
  - kind: clair
    managed: true
    overrides:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: quay-component
                operator: In
                values:
                - clair-app
            topologyKey: kubernetes.io/hostname
  - kind: redis
    managed: true
  - kind: horizontalpodautoscaler
    managed: true
  - kind: objectstorage
    managed: true
  - kind: route
    managed: true
  - kind: mirror
    managed: true
    overrides:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: quay-component
                operator: In
                values:
                - quay-mirror
            topologyKey: kubernetes.io/hostname
  - kind: monitoring
    managed: true
  - kind: tls
    managed: true
  - kind: clairpostgres
    managed: true
