apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: ca-rotation
spec:
  components:
    - kind: monitoring
      managed: false
    - kind: mirror
      managed: false
    - kind: horizontalpodautoscaler
      managed: false
    - kind: clair
      managed: false
    - kind: clairpostgres
      managed: false
    - kind: quay
      managed: true
    - kind: postgres
      managed: true
    - kind: redis
      managed: true
    - kind: objectstorage
      managed: true
    - kind: route
      managed: true
    - kind: tls
      managed: true
status:
  conditions:
  - type: ComponentHPAReady
    reason: ComponentNotManaged
    status: "True"
  - type: ComponentRouteReady
    reason: ComponentReady
    status: "True"
  - type: ComponentMonitoringReady
    reason: ComponentNotManaged
    status: "True"
  - type: ComponentPostgresReady
    reason: ComponentReady
    status: "True"
  - type: ComponentObjectStorageReady
    reason: ComponentReady
    status: "True"
  - type: ComponentClairReady
    reason: ComponentNotManaged
    status: "True"
  - type: ComponentClairPostgresReady
    reason: ComponentNotManaged
    status: "True"
  - type: ComponentTLSReady
    reason: ComponentReady
    status: "True"
  - type: ComponentRedisReady
    reason: ComponentReady
    status: "True"
  - type: ComponentQuayReady
    reason: ComponentReady
    status: "True"
  - type: ComponentMirrorReady
    reason: ComponentNotManaged
    status: "True"
  - type: Available
    reason: HealthChecksPassing
    status: "True"
  - type: ComponentsCreated
    reason: ComponentsCreationSuccess
    status: "True"
  - type: RolloutBlocked
    status: "False"
