apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: ca-rotation
spec:
  components:
    - kind: monitoring
      managed: false
    - kind: mirror
      managed: false
    - kind: horizontalpodautoscaler
      managed: false
    - kind: clair
      managed: false
    - kind: clairpostgres
      managed: false
