apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: skynet
spec:
  components:
    - kind: clair
      managed: true
      overrides:
        useEphemeralVolume: true
        volumeSize: 15Gi
        storageClassName: local-path