apiVersion: batch/v1
kind: Job
metadata:
  name: quay-postgres-init
  labels:
    quay-component: postgres
  annotations:
    quay-component: postgres
spec:
  template:
    metadata:
      name: quay-postgres-init
    spec:
      restartPolicy: Never
      volumes:
        - name: postgres-bootstrap
          secret:
            secretName: postgres-bootstrap
            defaultMode: 0777
            items:
              - key: create-extensions.sh
                path: create-extensions.sh
      containers:
        - name: quay-postgres-init
          image: centos/postgresql-10-centos7
          command: 
            - /opt/app-root/src/docker-entrypoint-initdb.d/create-extensions.sh
          env: 
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgres-config-secret
                  key: database-name
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-config-secret
                  key: database-root-password
          volumeMounts:
            - name: postgres-bootstrap
              mountPath: /opt/app-root/src/docker-entrypoint-initdb.d
