apiVersion: batch/v1
kind: Job
metadata:
  name: quay-postgres-init
spec:
  template:
    metadata:
      name: quay-postgres-init
    spec:
      restartPolicy: Never
      securityContext:
        fsGroup: 0
      volumes:
        - name: postgres-bootstrap
          secret:
            secretName: postgres-bootstrap
            defaultMode: 0777
            items:
              - key: create-extensions.sh
                path: create-extensions.sh
              - key: restore.sh
                path: restore.sh
      containers:
        - name: quay-postgres-init
          image: centos/postgresql-10-centos7
          command: 
            - /opt/app-root/src/docker-entrypoint-initdb.d/create-extensions.sh
          env: 
            - name: POSTGRESQL_DATABASE
              value: $(POSTGRES_DEPLOYMENT_NAME)
            - name: PGPASSWORD
              value: postgres
          volumeMounts:
            - name: postgres-bootstrap
              mountPath: /opt/app-root/src/docker-entrypoint-initdb.d
