apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    deploymentStrategy: Recreate
    skipSetup: true
    keepConfigDeployment: true
    externalAccess:
      hostname: quay.app.example.com
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
