apiVersion: redhatcop.redhat.io/v1alpha1
kind: QuayEcosystem
metadata:
  name: quayecosystem
spec:
  quay:
    imagePullSecretName: redhat-pull-secret
    deploymentStrategy: Recreate
    #sslCertificatesSecretName: custom-quay-ssl
    skipSetup: true
    keepConfigDeployment: true
    routeHost: {{ quay_url }}
  redis:
    imagePullSecretName: redhat-pull-secret
  clair:
    enabled: true
    imagePullSecretName: redhat-pull-secret
