# Overlay variant for upgrading to current Project Quay release.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../tmp
patchesStrategicMerge:
  - ./quay.deployment.patch.yaml
  - ./postgres.init.job.yaml
  - ./quay.upgrade.job.yaml
