apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: quayecosystems.cop.redhat.com
spec:
  group: cop.redhat.com
  names:
    kind: QuayEcosystem
    listKind: QuayEcosystemList
    plural: quayecosystems
    singular: quayecosystem
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
