apiVersion: batch/v1
kind: Job
metadata:
  name: clair-postgres-upgrade
  labels:
    quay-component: clair-postgres-upgrade
  annotations:
    quay-component: clair-postgres-upgrade
spec:
  template:
    spec:
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 180
      serviceAccountName: clair-postgres
      volumes:
        - name: clair-postgres-conf-sample
          configMap:
            name: clair-postgres-conf-sample
        - name: clair-postgres-13
          persistentVolumeClaim:
            claimName: clair-postgres-13
      containers:
        - name: clair-postgres-13
          image: centos/postgresql-13-centos7@sha256:71b24684d64da46f960682cc4216222a7e4ed8b1a31dd5a865b3e71afdea20d2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_MIGRATION_REMOTE_HOST
              value: $(CLAIR_POSTGRES_HOSTNAME)
            - name: POSTGRESQL_MIGRATION_ADMIN_PASSWORD
              value: postgres
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: "1000"
          volumeMounts:
            - name: clair-postgres-conf-sample
              mountPath: /usr/share/pgsql/postgresql.conf.sample
              subPath: postgresql.conf.sample
            - name: clair-postgres-13
              mountPath: /var/lib/pgsql/data
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
          command:
            - "run-postgresql"
          args:
            - "--version"
  backoffLimit: 20
