apiVersion: batch/v1
kind: Job
metadata:
  name: clair-postgres-upgrade
  labels:
    quay-component: clair-postgres-upgrade
  annotations:
    quay-component: clair-postgres-upgrade
spec:
  template:
    spec:
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 180
      serviceAccountName: clair-postgres
      volumes:
        - name: clair-postgres-conf-sample
          configMap:
            name: clair-postgres-conf-sample
        - name: postgres-data
          persistentVolumeClaim:
            claimName: clair-postgres
        - name: migration-data
          persistentVolumeClaim:
            claimName: clair-postgres-migration
      initContainers:
        - name: postgres-old
          image: centos/postgresql-12-centos7@sha256:be8803d45d64870f8dfd018f3110af62e2e1558d64191faea461005e1bd03243
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_UPGRADE
              value: copy
            - name: POSTGRESQL_USER
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: postgres
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: "1000"
          volumeMounts:
            - name: clair-postgres-conf-sample
              mountPath: /usr/share/pgsql/postgresql.conf.sample
              subPath: postgresql.conf.sample
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
            - name: migration-data
              mountPath: /var/lib/pgsql/backup
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
          command:
            - "/bin/bash"
            - "-c"
            - "cp -r /var/lib/pgsql/data /var/lib/pgsql/backup/clair && run-postgresql --help"

      containers:
        - name: postgres-new
          image: centos/postgresql-13-centos7@sha256:71b24684d64da46f960682cc4216222a7e4ed8b1a31dd5a865b3e71afdea20d2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_UPGRADE
              value: copy
            - name: POSTGRESQL_USER
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_ADMIN_PASSWORD
              value: postgres
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: "1000"
          volumeMounts:
            - name: clair-postgres-conf-sample
              mountPath: /usr/share/pgsql/postgresql.conf.sample
              subPath: postgresql.conf.sample
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
            - name: migration-data
              mountPath: /var/lib/pgsql/backup
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
          command:
            - "run-postgresql"
          args:
            - "--version"
  backoffLimit: 50
