# Overlay variant for upgrading to current Project Quay release.
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./clair-pg-upgrade.job.yaml
  - ./clair-pg-old.persistentvolumeclaim.yaml
  - ./clair-pg-old.deployment.yaml
patchesStrategicMerge:
  - ./clair.deployment.patch.yaml
  - ./clair-pg.deployment.patch.yaml
