---
apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  finalizers:
  - quay-operator/finalizer
  name: mirror
spec:
  components:
  - kind: clair
    managed: false
  - kind: clairpostgres
    managed: false
  - kind: quay
    managed: true
  - kind: postgres
    managed: true
  - kind: redis
    managed: true
  - kind: horizontalpodautoscaler
    managed: true
  - kind: objectstorage
    managed: true
  - kind: route
    managed: true
  - kind: mirror
    managed: true
  - kind: monitoring
    managed: true
  - kind: tls
    managed: true
status:
  conditions:
  - message: Horizontal pod autoscaler found
    reason: ComponentReady
    status: "True"
    type: ComponentHPAReady
  - message: Route admitted
    reason: ComponentReady
    status: "True"
    type: ComponentRouteReady
  - message: ServiceMonitor and PrometheusRules created
    reason: ComponentReady
    status: "True"
    type: ComponentMonitoringReady
  - message: Deployment mirror-quay-database healthy
    reason: ComponentReady
    status: "True"
    type: ComponentPostgresReady
  - message: Object bucket claim bound
    reason: ComponentReady
    status: "True"
    type: ComponentObjectStorageReady
  - message: Clair not managed by the operator
    reason: ComponentNotManaged
    status: "True"
    type: ComponentClairReady
  - message: ClairPostgres not managed by the operator
    reason: ComponentNotManaged
    status: "True"
    type: ComponentClairPostgresReady
  - message: Using cluster wildcard certs
    reason: ComponentReady
    status: "True"
    type: ComponentTLSReady
  - message: Deployment mirror-quay-redis healthy
    reason: ComponentReady
    status: "True"
    type: ComponentRedisReady
  - message: Quay component healthy
    reason: ComponentReady
    status: "True"
    type: ComponentQuayReady
  - message: Deployment mirror-quay-mirror healthy
    reason: ComponentReady
    status: "True"
    type: ComponentMirrorReady
  - message: All components reporting as healthy
    reason: HealthChecksPassing
    status: "True"
    type: Available
  - message: All registry components created
    reason: ComponentsCreationSuccess
    status: "True"
    type: ComponentsCreated
  - message: All objects created/updated successfully
    reason: ComponentsCreationSuccess
    status: "False"
    type: RolloutBlocked
---

