apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: quay-datastore
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
spec:
  ObjectBucketName: obc-skynet-registry-skynet-quay-datastore
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  bucketName: skynet-quay-datastore
  storageClassName: openshift-storage.noobaa.io
