apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: quay-alerts-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: quay-alerts-role
subjects:
  - kind: ServiceAccount
    name: prometheus-operator
    namespace: openshift-monitoring
