apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quay-metrics
  annotations:
    quay-component: monitoring
rules:
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
