apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: quay-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: quay-metrics
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
