apiVersion: apps/v1
kind: Deployment
metadata:
  name: quay-app
spec:
  template:
    spec:
      containers:
        - name: quay-app
          startupProbe:
            httpGet:
              path: /health/instance
              port: 8443
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /health/instance
              port: 8443
              scheme: HTTPS
          livelinessProbe:
            httpGet:
              path: /health/instance
              port: 8443
              scheme: HTTPS
