apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: clair-app
  annotations:
    quay-component: clair
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: clair-app
  minReplicas: 2
  maxReplicas: 10
  # TODO: Use custom Prometheus metrics (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-metrics-apis)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90
