apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quay-mirror
  annotations:
    quay-component: mirror
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quay-mirror
  minReplicas: 2
  maxReplicas: 20
  # TODO: Use custom Prometheus metrics (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#support-for-metrics-apis)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 90
