apiVersion: quay.redhat.com/v1
kind: QuayRegistry
metadata:
  name: clairpostgres-e2e
spec:
  components:
  - kind: horizontalpodautoscaler
    managed: false
  - kind: mirror
    managed: false
  - kind: monitoring
    managed: false
