apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: quay-serviceaccount
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - put
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - patch
      - update
      - watch
