apiVersion: batch/v1
kind: Job
metadata:
  name: quay-app-upgrade
  labels:
    quay-component: quay-app-upgrade
  annotations:
    quay-component: base
spec:
  template:
    metadata:
      name: quay-app-upgrade
      labels:
        quay-component: quay-app-upgrade
    spec:
      restartPolicy: OnFailure
      serviceAccountName: quay-app
      volumes:
        - name: config
          secret:
            secretName: quay-config-secret
        - name: extra-ca-certs
          configMap:
            name: cluster-service-ca
      containers:
        - name: quay-app-upgrade
          image: quay.io/projectquay/quay@sha256:5660d7174218e1cb21bf6ef406602dbe8c01c878c630a9f310fe3e5560d4c2cd
          args: ["migrate", "head"]
          env:
            - name: QE_K8S_CONFIG_SECRET
              # FIXME: Using `vars` is kinda ugly because it's basically templating, but this needs to be the generated `Secret` name...
              value: $(QE_K8S_CONFIG_SECRET)
            - name: QE_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DEBUGLOG
              value: "false"
            - name: WORKER_COUNT_WEB
              value: "4"
            - name: WORKER_COUNT_SECSCAN
              value: "2"
            - name: WORKER_COUNT_REGISTRY
              value: "8"
          ports:
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 1000m
              memory: 3Gi
            limits:
              cpu: 2000m
              memory: 8Gi
          volumeMounts:
            - name: config
              readOnly: false
              mountPath: /conf/stack
            - name: extra-ca-certs
              readOnly: true
              mountPath: /conf/stack/extra_ca_certs
