apiVersion: batch/v1
kind: Job
metadata:
  name: clair-postgres-upgrade
  labels:
    quay-component: clair-postgres-upgrade
  annotations:
    quay-component: clair-postgres-upgrade
spec:
  template:
    spec:
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 180
      serviceAccountName: clair-postgres
      volumes:
        - name: clair-postgres-conf-sample
          configMap:
            name: clair-postgres-conf-sample
        - name: clair-postgres-13
          persistentVolumeClaim:
            claimName: clair-postgres-13
      containers:
        - name: clair-postgres-13
          image: quay.io/sclorg/postgresql-13-c9s:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_MIGRATION_REMOTE_HOST
              valueFrom:
                secretKeyRef:
                  name: clair-config-secret
                  key: clair-db-host
            - name: POSTGRESQL_MIGRATION_ADMIN_PASSWORD
              value: postgres
            - name: POSTGRESQL_SHARED_BUFFERS
              value: 256MB
            - name: POSTGRESQL_MAX_CONNECTIONS
              value: "2000"
          volumeMounts:
            - name: clair-postgres-conf-sample
              mountPath: /usr/share/pgsql/postgresql.conf.sample
              subPath: postgresql.conf.sample
            - name: clair-postgres-13
              mountPath: /var/lib/pgsql/data
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
          command:
          - "/bin/sh"
          - "-c"
          args:
          - >
            run-postgresql --version || (echo "postgres migration command failed, cleaning up..." && rm -rf /var/lib/pgsql/data/* && exit 1)
  backoffLimit: 50
