apiVersion: v1
kind: Service
metadata:
  name: clair-postgres-old
  labels:
    quay-component: clair-postgres-old
  annotations:
    quay-component: clair-postgres-old
spec:
  type: ClusterIP
  ports:
    - port: 5432
      protocol: TCP
      name: postgres
      targetPort: 5432
  selector:
    quay-component: clair-postgres-old
