apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: quay-database
  labels:
    quay-component: postgres
  annotations:
    quay-component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
