apiVersion: apps/v1
kind: Deployment
metadata:
  name: skynet-quay-app
spec:
  template:
    metadata:
      annotations:
        a1: TESTING
        a2: TESTING
      labels:
        l1: TESTING
        l2: TESTING
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skynet-quay-database
spec:
  template:
    metadata:
      annotations:
        a1: TESTING
        a2: TESTING
      labels:
        l1: TESTING
        l2: TESTING
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skynet-clair-app
spec:
  template:
    metadata:
      annotations:
        a1: TESTING
        a2: TESTING
      labels:
        l1: TESTING
        l2: TESTING
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skynet-quay-redis
spec:
  template:
    metadata:
      annotations:
        a1: TESTING
        a2: TESTING
      labels:
        l1: TESTING
        l2: TESTING
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skynet-quay-mirror
spec:
  template:
    metadata:
      annotations:
        a1: TESTING
        a2: TESTING
      labels:
        l1: TESTING
        l2: TESTING
